<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->headScript() ?>
    <?php echo $this->headMeta() ?>

</head>
<body>
<div class="container">
    <div id="header" class="span-24 last">
        <h2><?php echo 'Загружена страница: ' . $this->pagename; ?> </h2>
        <h2>-----------------------------------</h2>
    </div>
    <div id="content" class="span-17 colborder">
        <?php echo $this->layout()->content; ?>
    </div>
    <div id="sidebar" class="span-6 last">
        <p>Sidebar</p>
    </div>
    <div id="footer" class="span-24 last">
        <h2>Подвал</h2>
    </div>
</div>
</body>

</html>
